uint16_t lhs = (uint16_t)a;
uint16_t rhs = (uint16_t)b;
uint8_t carry_in = EFLAGS.CF;
uint16_t result = lhs + rhs + carry_in;
EFLAGS.CF = (uint64_t)lhs + rhs + carry_in > UINT16_MAX;
EFLAGS.AF = ((lhs ^ rhs ^ result) & 0x10) != 0;
EFLAGS.OF = ((~(lhs ^ rhs)) & (lhs ^ result) & 0x8000) != 0;
EFLAGS.PF = parity_even((uint8_t)result);
EFLAGS.ZF = result == 0;
EFLAGS.SF = (int16_t)result < 0;
