// Pseudocode vocabulary: bit-exact operations that cannot be expressed as
// native dword C++ (policy-correct IEEE-754, conversions, conditional RMW,
// packing, matrix and texture models). One inline wrapper per helper
// arity; the .h pseudocode calls these names instead of test:: helpers.
// Generated by tools/gen_pairs.py; do not edit by hand.
#pragma once

#include "ops/oracle.hpp"

inline u32 absdiff_i32(u32 a, u32 b) { return lgpu::test::oracle_absdiff_i32(a, b); }
inline u32 atomic_v_buff_add_i32(u32 old, u32 src) { return lgpu::test::oracle_atomic_v_buff_add_i32(old, src); }
inline u32 atomic_v_buff_and_b32(u32 old, u32 src) { return lgpu::test::oracle_atomic_v_buff_and_b32(old, src); }
inline u32 atomic_v_buff_max_i32(u32 old, u32 src) { return lgpu::test::oracle_atomic_v_buff_max_i32(old, src); }
inline u32 atomic_v_buff_max_u32(u32 old, u32 src) { return lgpu::test::oracle_atomic_v_buff_max_u32(old, src); }
inline u32 atomic_v_buff_min_i32(u32 old, u32 src) { return lgpu::test::oracle_atomic_v_buff_min_i32(old, src); }
inline u32 atomic_v_buff_min_u32(u32 old, u32 src) { return lgpu::test::oracle_atomic_v_buff_min_u32(old, src); }
inline u32 atomic_v_buff_or_b32(u32 old, u32 src) { return lgpu::test::oracle_atomic_v_buff_or_b32(old, src); }
inline u32 atomic_v_buff_swap_b32(u32 old, u32 src) { return lgpu::test::oracle_atomic_v_buff_swap_b32(old, src); }
inline u32 atomic_v_buff_xor_b32(u32 old, u32 src) { return lgpu::test::oracle_atomic_v_buff_xor_b32(old, src); }
inline u32 bcnt0_u32(u32 a) { return lgpu::test::oracle_bcnt0_u32(a); }
inline u32 bfe_i32(u32 a, u32 offset, u32 width) { return lgpu::test::oracle_bfe_i32(a, offset, width); }
inline u32 bfe_u32(u32 a, u32 offset, u32 width) { return lgpu::test::oracle_bfe_u32(a, offset, width); }
inline u32 bfm_b32(u32 mask, u32 offset) { return lgpu::test::oracle_bfm_b32(mask, offset); }
inline u32 bfrev_b32(u32 a) { return lgpu::test::oracle_bfrev_b32(a); }
inline u32 bitalign_b32(u32 lo, u32 hi, u32 n) { return lgpu::test::oracle_bitalign_b32(lo, hi, n); }
inline u32 bitcmp0_b32(u32 a, u32 bit) { return lgpu::test::oracle_bitcmp0_b32(a, bit); }
inline u32 bitcmp1_b32(u32 a, u32 bit) { return lgpu::test::oracle_bitcmp1_b32(a, bit); }
inline u32 bitcmprev0(u32 a, u32 bit) { return lgpu::test::oracle_bitcmprev0(a, bit); }
inline u32 bitcmprev1(u32 a, u32 bit) { return lgpu::test::oracle_bitcmprev1(a, bit); }
inline u32 bytealign_b32(u32 lo, u32 hi, u32 n) { return lgpu::test::oracle_bytealign_b32(lo, hi, n); }
inline u32 byteperm_b32(u32 a, u32 b, u32 sel) { return lgpu::test::oracle_byteperm_b32(a, b, sel); }
inline u32 clb_u32(u32 a) { return lgpu::test::oracle_clb_u32(a); }
inline u32 clo_u32(u32 a) { return lgpu::test::oracle_clo_u32(a); }
inline u32 cmp_eq_f16(u32 a, u32 b) { return lgpu::test::oracle_cmp_eq_f16(a, b); }
inline u32 cmp_eq_f32(u32 a, u32 b) { return lgpu::test::oracle_cmp_eq_f32(a, b); }
inline u32 cmp_eq_f64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_eq_f64(a, b, policy); }
inline u32 cmp_eq_i16(u32 a, u32 b) { return lgpu::test::oracle_cmp_eq_i16(a, b); }
inline u32 cmp_eq_i32(u32 a, u32 b) { return lgpu::test::oracle_cmp_eq_i32(a, b); }
inline u32 cmp_eq_i64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_eq_i64(a, b, policy); }
inline u32 cmp_eq_u16(u32 a, u32 b) { return lgpu::test::oracle_cmp_eq_u16(a, b); }
inline u32 cmp_eq_u32(u32 a, u32 b) { return lgpu::test::oracle_cmp_eq_u32(a, b); }
inline u32 cmp_eq_u64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_eq_u64(a, b, policy); }
inline u32 cmp_ge_f16(u32 a, u32 b) { return lgpu::test::oracle_cmp_ge_f16(a, b); }
inline u32 cmp_ge_f32(u32 a, u32 b) { return lgpu::test::oracle_cmp_ge_f32(a, b); }
inline u32 cmp_ge_f64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_ge_f64(a, b, policy); }
inline u32 cmp_ge_i16(u32 a, u32 b) { return lgpu::test::oracle_cmp_ge_i16(a, b); }
inline u32 cmp_ge_i32(u32 a, u32 b) { return lgpu::test::oracle_cmp_ge_i32(a, b); }
inline u32 cmp_ge_i64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_ge_i64(a, b, policy); }
inline u32 cmp_ge_u16(u32 a, u32 b) { return lgpu::test::oracle_cmp_ge_u16(a, b); }
inline u32 cmp_ge_u32(u32 a, u32 b) { return lgpu::test::oracle_cmp_ge_u32(a, b); }
inline u32 cmp_ge_u64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_ge_u64(a, b, policy); }
inline u32 cmp_gt_f16(u32 a, u32 b) { return lgpu::test::oracle_cmp_gt_f16(a, b); }
inline u32 cmp_gt_f32(u32 a, u32 b) { return lgpu::test::oracle_cmp_gt_f32(a, b); }
inline u32 cmp_gt_f64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_gt_f64(a, b, policy); }
inline u32 cmp_gt_i16(u32 a, u32 b) { return lgpu::test::oracle_cmp_gt_i16(a, b); }
inline u32 cmp_gt_i32(u32 a, u32 b) { return lgpu::test::oracle_cmp_gt_i32(a, b); }
inline u32 cmp_gt_i64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_gt_i64(a, b, policy); }
inline u32 cmp_gt_u16(u32 a, u32 b) { return lgpu::test::oracle_cmp_gt_u16(a, b); }
inline u32 cmp_gt_u32(u32 a, u32 b) { return lgpu::test::oracle_cmp_gt_u32(a, b); }
inline u32 cmp_gt_u64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_gt_u64(a, b, policy); }
inline u32 cmp_le_f16(u32 a, u32 b) { return lgpu::test::oracle_cmp_le_f16(a, b); }
inline u32 cmp_le_f32(u32 a, u32 b) { return lgpu::test::oracle_cmp_le_f32(a, b); }
inline u32 cmp_le_f64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_le_f64(a, b, policy); }
inline u32 cmp_le_i16(u32 a, u32 b) { return lgpu::test::oracle_cmp_le_i16(a, b); }
inline u32 cmp_le_i32(u32 a, u32 b) { return lgpu::test::oracle_cmp_le_i32(a, b); }
inline u32 cmp_le_i64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_le_i64(a, b, policy); }
inline u32 cmp_le_u16(u32 a, u32 b) { return lgpu::test::oracle_cmp_le_u16(a, b); }
inline u32 cmp_le_u32(u32 a, u32 b) { return lgpu::test::oracle_cmp_le_u32(a, b); }
inline u32 cmp_le_u64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_le_u64(a, b, policy); }
inline u32 cmp_lg_f16(u32 a, u32 b) { return lgpu::test::oracle_cmp_lg_f16(a, b); }
inline u32 cmp_lg_f32(u32 a, u32 b) { return lgpu::test::oracle_cmp_lg_f32(a, b); }
inline u32 cmp_lg_f64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_lg_f64(a, b, policy); }
inline u32 cmp_lt_f16(u32 a, u32 b) { return lgpu::test::oracle_cmp_lt_f16(a, b); }
inline u32 cmp_lt_f32(u32 a, u32 b) { return lgpu::test::oracle_cmp_lt_f32(a, b); }
inline u32 cmp_lt_f64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_lt_f64(a, b, policy); }
inline u32 cmp_lt_i16(u32 a, u32 b) { return lgpu::test::oracle_cmp_lt_i16(a, b); }
inline u32 cmp_lt_i32(u32 a, u32 b) { return lgpu::test::oracle_cmp_lt_i32(a, b); }
inline u32 cmp_lt_i64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_lt_i64(a, b, policy); }
inline u32 cmp_lt_u16(u32 a, u32 b) { return lgpu::test::oracle_cmp_lt_u16(a, b); }
inline u32 cmp_lt_u32(u32 a, u32 b) { return lgpu::test::oracle_cmp_lt_u32(a, b); }
inline u32 cmp_lt_u64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_lt_u64(a, b, policy); }
inline u32 cmp_ne_u32(u32 a, u32 b) { return lgpu::test::oracle_cmp_ne_u32(a, b); }
inline u32 cmp_ne_u64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_ne_u64(a, b, policy); }
inline u32 cmp_neq_f16(u32 a, u32 b) { return lgpu::test::oracle_cmp_neq_f16(a, b); }
inline u32 cmp_neq_f32(u32 a, u32 b) { return lgpu::test::oracle_cmp_neq_f32(a, b); }
inline u32 cmp_neq_f64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_neq_f64(a, b, policy); }
inline u32 cmp_neq_i16(u32 a, u32 b) { return lgpu::test::oracle_cmp_neq_i16(a, b); }
inline u32 cmp_neq_i32(u32 a, u32 b) { return lgpu::test::oracle_cmp_neq_i32(a, b); }
inline u32 cmp_neq_i64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_neq_i64(a, b, policy); }
inline u32 cmp_neq_u16(u32 a, u32 b) { return lgpu::test::oracle_cmp_neq_u16(a, b); }
inline u32 cmp_neq_u32(u32 a, u32 b) { return lgpu::test::oracle_cmp_neq_u32(a, b); }
inline u32 cmp_neq_u64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_neq_u64(a, b, policy); }
inline u32 cmp_nge_f16(u32 a, u32 b) { return lgpu::test::oracle_cmp_nge_f16(a, b); }
inline u32 cmp_nge_f32(u32 a, u32 b) { return lgpu::test::oracle_cmp_nge_f32(a, b); }
inline u32 cmp_nge_f64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_nge_f64(a, b, policy); }
inline u32 cmp_ngt_f16(u32 a, u32 b) { return lgpu::test::oracle_cmp_ngt_f16(a, b); }
inline u32 cmp_ngt_f32(u32 a, u32 b) { return lgpu::test::oracle_cmp_ngt_f32(a, b); }
inline u32 cmp_ngt_f32_std(u32 a, u32 b) { return lgpu::test::oracle_cmp_ngt_f32_std(a, b); }
inline u32 cmp_ngt_f64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_ngt_f64(a, b, policy); }
inline u32 cmp_nle_f16(u32 a, u32 b) { return lgpu::test::oracle_cmp_nle_f16(a, b); }
inline u32 cmp_nle_f32(u32 a, u32 b) { return lgpu::test::oracle_cmp_nle_f32(a, b); }
inline u32 cmp_nle_f32_std(u32 a, u32 b) { return lgpu::test::oracle_cmp_nle_f32_std(a, b); }
inline u32 cmp_nle_f64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_nle_f64(a, b, policy); }
inline u32 cmp_nlg_f16(u32 a, u32 b) { return lgpu::test::oracle_cmp_nlg_f16(a, b); }
inline u32 cmp_nlg_f32(u32 a, u32 b) { return lgpu::test::oracle_cmp_nlg_f32(a, b); }
inline u32 cmp_nlg_f64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_nlg_f64(a, b, policy); }
inline u32 cmp_nlt_f16(u32 a, u32 b) { return lgpu::test::oracle_cmp_nlt_f16(a, b); }
inline u32 cmp_nlt_f32(u32 a, u32 b) { return lgpu::test::oracle_cmp_nlt_f32(a, b); }
inline u32 cmp_nlt_f64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_nlt_f64(a, b, policy); }
inline u32 cmp_o_f16(u32 a, u32 b) { return lgpu::test::oracle_cmp_o_f16(a, b); }
inline u32 cmp_o_f32(u32 a, u32 b) { return lgpu::test::oracle_cmp_o_f32(a, b); }
inline u32 cmp_o_f64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_o_f64(a, b, policy); }
inline u32 cmp_tru(u32 a, u32 b) { return lgpu::test::oracle_cmp_tru(a, b); }
inline u32 cmp_tru(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_tru(a, b, policy); }
inline u32 cmp_u_f16(u32 a, u32 b) { return lgpu::test::oracle_cmp_u_f16(a, b); }
inline u32 cmp_u_f32(u32 a, u32 b) { return lgpu::test::oracle_cmp_u_f32(a, b); }
inline u32 cmp_u_f64(u64 a, u64 b, const lgpu::test::FpPolicy& policy) { return lgpu::test::oracle_cmp_u_f64(a, b, policy); }
inline u32 cmpclass_f16(u32 mask, u32 v) { return lgpu::test::oracle_cmpclass_f16(mask, v); }
inline u32 cmpclass_f32(u32 mask, u32 v) { return lgpu::test::oracle_cmpclass_f32(mask, v); }
inline u64 cmpclass_f64(u64 mask, u64 v) { return lgpu::test::oracle_cmpclass_f64(mask, v); }
inline u32 copysign_imm_f32(u32 src, u32 imm, const lgpu::test::FpPolicy& p2) { return lgpu::test::oracle_copysign_imm_f32(src, imm, p2); }
inline u32 cto_u32(u32 a) { return lgpu::test::oracle_cto_u32(a); }
inline u32 ctz_u32(u32 a) { return lgpu::test::oracle_ctz_u32(a); }
inline u32 cubes(u32 s0, u32 s1, u32 s2) { return lgpu::test::oracle_cubes(s0, s1, s2); }
inline u32 cubet(u32 s0, u32 s1, u32 s2) { return lgpu::test::oracle_cubet(s0, s1, s2); }
inline u32 dp4a_i8_i8_i32(u32 a, u32 b) { return lgpu::test::oracle_dp4a_i8_i8_i32(a, b); }
inline u32 dp4a_i8_u8_i32(u32 a, u32 b) { return lgpu::test::oracle_dp4a_i8_u8_i32(a, b); }
inline u32 dp4a_u8_i8_i32(u32 a, u32 b) { return lgpu::test::oracle_dp4a_u8_i8_i32(a, b); }
inline u32 dp4a_u8_u8_i32(u32 a, u32 b) { return lgpu::test::oracle_dp4a_u8_u8_i32(a, b); }
inline u32 fcvt_f16_i16(u32 a) { return lgpu::test::oracle_fcvt_f16_i16(a); }
inline u32 fcvt_f16_u16(u32 a) { return lgpu::test::oracle_fcvt_f16_u16(a); }
inline u32 fcvt_f32_u80(u32 a) { return lgpu::test::oracle_fcvt_f32_u80(a); }
inline u32 fcvt_f32_u81(u32 a) { return lgpu::test::oracle_fcvt_f32_u81(a); }
inline u32 fcvt_f32_u82(u32 a) { return lgpu::test::oracle_fcvt_f32_u82(a); }
inline u32 fcvt_f32_u83(u32 a) { return lgpu::test::oracle_fcvt_f32_u83(a); }
inline u32 fcvt_i16_f16(u32 a) { return lgpu::test::oracle_fcvt_i16_f16(a); }
inline u32 fcvt_f32off_i4(u32 a) { return lgpu::test::oracle_fcvt_f32off_i4(a); }
inline u32 fcvt_i32flr_f32(u32 a) { return lgpu::test::oracle_fcvt_i32flr_f32(a); }
inline u32 fcvt_i32rpi_f32(u32 a) { return lgpu::test::oracle_fcvt_i32rpi_f32(a); }
inline u32 fcvt_u16_f16(u32 a) { return lgpu::test::oracle_fcvt_u16_f16(a); }
inline u32 frexp_exp_i32_f32(u32 a) { return lgpu::test::oracle_frexp_exp_i32_f32(a); }
inline u32 frexp_exp_i32_f64(u64 a) { return lgpu::test::oracle_frexp_exp_i32_f64(a); }
inline u32 frexp_mant_f32(u32 a) { return lgpu::test::oracle_frexp_mant_f32(a); }
inline u64 frexp_mant_f64(u64 a) { return lgpu::test::oracle_frexp_mant_f64(a); }
inline u32 mad24_i32(u32 a, u32 b, u32 c) { return lgpu::test::oracle_mad24_i32(a, b, c); }
inline u32 mad24_u32(u32 a, u32 b, u32 c) { return lgpu::test::oracle_mad24_u32(a, b, c); }
inline u32 mad_i32(u32 a, u32 b, u32 c) { return lgpu::test::oracle_mad_i32(a, b, c); }
inline u32 max3_i32(u32 a, u32 b, u32 c) { return lgpu::test::oracle_max3_i32(a, b, c); }
inline u32 max3_u32(u32 a, u32 b, u32 c) { return lgpu::test::oracle_max3_u32(a, b, c); }
inline u32 max_i32(u32 a, u32 b) { return lgpu::test::oracle_max_i32(a, b); }
inline u32 max_u32(u32 a, u32 b) { return lgpu::test::oracle_max_u32(a, b); }
inline u32 mbcnt_u32(u32 v, u32 mask) { return lgpu::test::oracle_mbcnt_u32(v, mask); }
inline u32 med3_i32(u32 a, u32 b, u32 c) { return lgpu::test::oracle_med3_i32(a, b, c); }
inline u32 med3_u32(u32 a, u32 b, u32 c) { return lgpu::test::oracle_med3_u32(a, b, c); }
inline u32 min3_i32(u32 a, u32 b, u32 c) { return lgpu::test::oracle_min3_i32(a, b, c); }
inline u32 min3_u32(u32 a, u32 b, u32 c) { return lgpu::test::oracle_min3_u32(a, b, c); }
inline u32 min_i32(u32 a, u32 b) { return lgpu::test::oracle_min_i32(a, b); }
inline u32 min_u32(u32 a, u32 b) { return lgpu::test::oracle_min_u32(a, b); }
inline u32 mul24_hi_i32(u32 a, u32 b) { return lgpu::test::oracle_mul24_hi_i32(a, b); }
inline u32 mul24_hi_u32(u32 a, u32 b) { return lgpu::test::oracle_mul24_hi_u32(a, b); }
inline u32 mul24_i32(u32 a, u32 b) { return lgpu::test::oracle_mul24_i32(a, b); }
inline u32 mul24_u32(u32 a, u32 b) { return lgpu::test::oracle_mul24_u32(a, b); }
inline u32 mul_hi_i32(u32 a, u32 b) { return lgpu::test::oracle_mul_hi_i32(a, b); }
inline u32 mul_hi_u32(u32 a, u32 b) { return lgpu::test::oracle_mul_hi_u32(a, b); }
inline u32 mul_u32(u32 a, u32 b) { return lgpu::test::oracle_mul_u32(a, b); }
inline u32 pack_f16rtz_f32(u32 a) { return lgpu::test::oracle_pack_f16rtz_f32(a); }
inline u32 pack_i16_i32(u32 a, u32 b) { return lgpu::test::oracle_pack_i16_i32(a, b); }
inline u32 pack_i8_i32(u32 a, u32 b, u32 c) { return lgpu::test::oracle_pack_i8_i32(a, b, c); }
inline u32 pack_snorm16_f32(u32 a) { return lgpu::test::oracle_pack_snorm16_f32(a); }
inline u32 pack_u16_u32(u32 a, u32 b) { return lgpu::test::oracle_pack_u16_u32(a, b); }
inline u32 pack_u8_f32(u32 a, u32 b, u32 c) { return lgpu::test::oracle_pack_u8_f32(a, b, c); }
inline u32 pack_u8_u32(u32 a, u32 b, u32 c) { return lgpu::test::oracle_pack_u8_u32(a, b, c); }
inline u32 pack_unorm16_f32(u32 a) { return lgpu::test::oracle_pack_unorm16_f32(a); }
inline u32 quadmask(u32 a) { return lgpu::test::oracle_quadmask(a); }
inline u32 rotr_b32(u32 a, u32 n) { return lgpu::test::oracle_rotr_b32(a, n); }
inline u32 rotrrev_b32(u32 count, u32 data) { return lgpu::test::oracle_rotrrev_b32(count, data); }
inline u32 s_addc_u32(u32 src, u32 imm, u32 carry_in) { return lgpu::test::oracle_s_addc_u32(src, imm, carry_in); }
inline u32 select_b32(u32 a, u32 b, u32 sel) { return lgpu::test::oracle_select_b32(a, b, sel); }
inline u32 sext_i32_i16(u32 a) { return lgpu::test::oracle_sext_i32_i16(a); }
inline u32 sext_i32_i8(u32 a) { return lgpu::test::oracle_sext_i32_i8(a); }
inline u64 sm_add_u64(u64 old, u64 src) { return lgpu::test::oracle_sm_add_u64(old, src); }
inline u32 sm_and_b32(u32 old, u32 src) { return lgpu::test::oracle_sm_and_b32(old, src); }
inline u64 sm_and_b64(u64 old, u64 src) { return lgpu::test::oracle_sm_and_b64(old, src); }
inline u32 sm_cmpswap_eq_u32(u32 old, u32 cmp, u32 swap) { return lgpu::test::oracle_sm_cmpswap_eq_u32(old, cmp, swap); }
inline u64 sm_cmpswap_eq_u64(u64 old, u64 cmp, u64 swap) { return lgpu::test::oracle_sm_cmpswap_eq_u64(old, cmp, swap); }
inline u32 sm_cmpswap_gt_f32(u32 old, u32 data) { return lgpu::test::oracle_sm_cmpswap_gt_f32(old, data); }
inline u64 sm_cmpswap_gt_f64(u64 old, u64 data) { return lgpu::test::oracle_sm_cmpswap_gt_f64(old, data); }
inline u32 sm_cmpswap_lt_f32(u32 old, u32 data) { return lgpu::test::oracle_sm_cmpswap_lt_f32(old, data); }
inline u64 sm_cmpswap_lt_f64(u64 old, u64 data) { return lgpu::test::oracle_sm_cmpswap_lt_f64(old, data); }
inline u32 sm_dec_u32(u32 old, u32 bound) { return lgpu::test::oracle_sm_dec_u32(old, bound); }
inline u64 sm_dec_u64(u64 old, u64 bound) { return lgpu::test::oracle_sm_dec_u64(old, bound); }
inline u32 sm_inc_u32(u32 old, u32 bound) { return lgpu::test::oracle_sm_inc_u32(old, bound); }
inline u64 sm_inc_u64(u64 old, u64 bound) { return lgpu::test::oracle_sm_inc_u64(old, bound); }
inline u32 sm_max_i32(u32 old, u32 src) { return lgpu::test::oracle_sm_max_i32(old, src); }
inline u64 sm_max_i64(u64 old, u64 src) { return lgpu::test::oracle_sm_max_i64(old, src); }
inline u32 sm_max_u32(u32 old, u32 src) { return lgpu::test::oracle_sm_max_u32(old, src); }
inline u64 sm_max_u64(u64 old, u64 src) { return lgpu::test::oracle_sm_max_u64(old, src); }
inline u32 sm_min_i32(u32 old, u32 src) { return lgpu::test::oracle_sm_min_i32(old, src); }
inline u64 sm_min_i64(u64 old, u64 src) { return lgpu::test::oracle_sm_min_i64(old, src); }
inline u32 sm_min_u32(u32 old, u32 src) { return lgpu::test::oracle_sm_min_u32(old, src); }
inline u64 sm_min_u64(u64 old, u64 src) { return lgpu::test::oracle_sm_min_u64(old, src); }
inline u32 sm_or_b32(u32 old, u32 src) { return lgpu::test::oracle_sm_or_b32(old, src); }
inline u64 sm_or_b64(u64 old, u64 src) { return lgpu::test::oracle_sm_or_b64(old, src); }
inline u32 sm_rsub_u32(u32 old, u32 src) { return lgpu::test::oracle_sm_rsub_u32(old, src); }
inline u64 sm_rsub_u64(u64 old, u64 src) { return lgpu::test::oracle_sm_rsub_u64(old, src); }
inline u32 sm_sub_u32(u32 old, u32 src) { return lgpu::test::oracle_sm_sub_u32(old, src); }
inline u64 sm_sub_u64(u64 old, u64 src) { return lgpu::test::oracle_sm_sub_u64(old, src); }
inline u32 sm_swap_b32(u32 old, u32 src) { return lgpu::test::oracle_sm_swap_b32(old, src); }
inline u64 sm_swap_b64(u64 old, u64 src) { return lgpu::test::oracle_sm_swap_b64(old, src); }
inline u32 sm_xor_b32(u32 old, u32 src) { return lgpu::test::oracle_sm_xor_b32(old, src); }
inline u64 sm_xor_b64(u64 old, u64 src) { return lgpu::test::oracle_sm_xor_b64(old, src); }
inline u32 sra_b32(u32 a, u32 n) { return lgpu::test::oracle_sra_b32(a, n); }
inline u64 sra_b64(u64 a, u32 n) { return lgpu::test::oracle_sra_b64(a, n); }
inline u32 srarev_b32(u32 count, u32 data) { return lgpu::test::oracle_srarev_b32(count, data); }
inline u32 sub_u32_value(u32 a, u32 b) { return lgpu::test::oracle_sub_u32_value(a, b); }
inline u32 v_bcnt1_u32(u32 a) { return lgpu::test::oracle_v_bcnt1_u32(a); }
inline u64 v_buff_add_i64(u64 old, u64 src) { return lgpu::test::oracle_v_buff_add_i64(old, src); }
inline u64 v_buff_and_b64(u64 old, u64 src) { return lgpu::test::oracle_v_buff_and_b64(old, src); }
inline u32 v_buff_cmpswap_b32(u32 old, u32 cmp, u32 swap) { return lgpu::test::oracle_v_buff_cmpswap_b32(old, cmp, swap); }
inline u64 v_buff_cmpswap_b64(u64 old, u64 cmp, u64 swap) { return lgpu::test::oracle_v_buff_cmpswap_b64(old, cmp, swap); }
inline u32 v_buff_dec_u32(u32 old, u32 bound) { return lgpu::test::oracle_v_buff_dec_u32(old, bound); }
inline u64 v_buff_dec_u64(u64 old, u64 bound) { return lgpu::test::oracle_v_buff_dec_u64(old, bound); }
inline u32 v_buff_inc_u32(u32 old, u32 bound) { return lgpu::test::oracle_v_buff_inc_u32(old, bound); }
inline u64 v_buff_inc_u64(u64 old, u64 bound) { return lgpu::test::oracle_v_buff_inc_u64(old, bound); }
inline u64 v_buff_max_i64(u64 old, u64 src) { return lgpu::test::oracle_v_buff_max_i64(old, src); }
inline u64 v_buff_max_u64(u64 old, u64 src) { return lgpu::test::oracle_v_buff_max_u64(old, src); }
inline u64 v_buff_min_i64(u64 old, u64 src) { return lgpu::test::oracle_v_buff_min_i64(old, src); }
inline u64 v_buff_min_u64(u64 old, u64 src) { return lgpu::test::oracle_v_buff_min_u64(old, src); }
inline u64 v_buff_or_b64(u64 old, u64 src) { return lgpu::test::oracle_v_buff_or_b64(old, src); }
inline u32 v_buff_sub_i32(u32 old, u32 src) { return lgpu::test::oracle_v_buff_sub_i32(old, src); }
inline u64 v_buff_sub_i64(u64 old, u64 src) { return lgpu::test::oracle_v_buff_sub_i64(old, src); }
inline u64 v_buff_swap_b64(u64 old, u64 src) { return lgpu::test::oracle_v_buff_swap_b64(old, src); }
inline u64 v_buff_xor_b64(u64 old, u64 src) { return lgpu::test::oracle_v_buff_xor_b64(old, src); }
inline u32 v_clz_u32(u32 a) { return lgpu::test::oracle_v_clz_u32(a); }
inline u32 v_flat_add_i32(u32 old, u32 src) { return lgpu::test::oracle_v_flat_add_i32(old, src); }
inline u64 v_flat_add_i64(u64 old, u64 src) { return lgpu::test::oracle_v_flat_add_i64(old, src); }
inline u32 v_flat_and_b32(u32 old, u32 src) { return lgpu::test::oracle_v_flat_and_b32(old, src); }
inline u64 v_flat_and_b64(u64 old, u64 src) { return lgpu::test::oracle_v_flat_and_b64(old, src); }
inline u32 v_flat_cmpswap_b32(u32 old, u32 cmp, u32 swap) { return lgpu::test::oracle_v_flat_cmpswap_b32(old, cmp, swap); }
inline u64 v_flat_cmpswap_b64(u64 old, u64 cmp, u64 swap) { return lgpu::test::oracle_v_flat_cmpswap_b64(old, cmp, swap); }
inline u32 v_flat_dec_u32(u32 old, u32 bound) { return lgpu::test::oracle_v_flat_dec_u32(old, bound); }
inline u64 v_flat_dec_u64(u64 old, u64 bound) { return lgpu::test::oracle_v_flat_dec_u64(old, bound); }
inline u32 v_flat_inc_u32(u32 old, u32 bound) { return lgpu::test::oracle_v_flat_inc_u32(old, bound); }
inline u64 v_flat_inc_u64(u64 old, u64 bound) { return lgpu::test::oracle_v_flat_inc_u64(old, bound); }
inline u32 v_flat_max_i32(u32 old, u32 src) { return lgpu::test::oracle_v_flat_max_i32(old, src); }
inline u64 v_flat_max_i64(u64 old, u64 src) { return lgpu::test::oracle_v_flat_max_i64(old, src); }
inline u32 v_flat_max_u32(u32 old, u32 src) { return lgpu::test::oracle_v_flat_max_u32(old, src); }
inline u64 v_flat_max_u64(u64 old, u64 src) { return lgpu::test::oracle_v_flat_max_u64(old, src); }
inline u32 v_flat_min_i32(u32 old, u32 src) { return lgpu::test::oracle_v_flat_min_i32(old, src); }
inline u64 v_flat_min_i64(u64 old, u64 src) { return lgpu::test::oracle_v_flat_min_i64(old, src); }
inline u32 v_flat_min_u32(u32 old, u32 src) { return lgpu::test::oracle_v_flat_min_u32(old, src); }
inline u64 v_flat_min_u64(u64 old, u64 src) { return lgpu::test::oracle_v_flat_min_u64(old, src); }
inline u32 v_flat_or_b32(u32 old, u32 src) { return lgpu::test::oracle_v_flat_or_b32(old, src); }
inline u64 v_flat_or_b64(u64 old, u64 src) { return lgpu::test::oracle_v_flat_or_b64(old, src); }
inline u32 v_flat_sub_i32(u32 old, u32 src) { return lgpu::test::oracle_v_flat_sub_i32(old, src); }
inline u64 v_flat_sub_i64(u64 old, u64 src) { return lgpu::test::oracle_v_flat_sub_i64(old, src); }
inline u32 v_flat_swap_b32(u32 old, u32 src) { return lgpu::test::oracle_v_flat_swap_b32(old, src); }
inline u64 v_flat_swap_b64(u64 old, u64 src) { return lgpu::test::oracle_v_flat_swap_b64(old, src); }
inline u32 v_flat_xor_b32(u32 old, u32 src) { return lgpu::test::oracle_v_flat_xor_b32(old, src); }
inline u64 v_flat_xor_b64(u64 old, u64 src) { return lgpu::test::oracle_v_flat_xor_b64(old, src); }
inline u32 v_interp_1_f32(u32 s0, u32 s1) { return lgpu::test::oracle_v_interp_1_f32(s0, s1); }
inline u32 v_mma(u32 a, u32 b, u32 c, bool signed_bytes) { return lgpu::test::oracle_v_mma(a, b, c, signed_bytes); }
inline u32 v_pack_f16rtz_f32(u32 a, u32 b) { return lgpu::test::oracle_v_pack_f16rtz_f32(a, b); }
inline u32 v_tex_add_i32(u32 old, u32 src) { return lgpu::test::oracle_v_tex_add_i32(old, src); }
inline u32 v_tex_and_b32(u32 old, u32 src) { return lgpu::test::oracle_v_tex_and_b32(old, src); }
inline u32 v_tex_cmpswap_b32(u32 old, u32 cmp, u32 swap) { return lgpu::test::oracle_v_tex_cmpswap_b32(old, cmp, swap); }
inline u32 v_tex_dec_u32(u32 old, u32 bound) { return lgpu::test::oracle_v_tex_dec_u32(old, bound); }
inline u32 v_tex_inc_u32(u32 old, u32 bound) { return lgpu::test::oracle_v_tex_inc_u32(old, bound); }
inline u32 v_tex_max_i32(u32 old, u32 src) { return lgpu::test::oracle_v_tex_max_i32(old, src); }
inline u32 v_tex_max_u32(u32 old, u32 src) { return lgpu::test::oracle_v_tex_max_u32(old, src); }
inline u32 v_tex_min_i32(u32 old, u32 src) { return lgpu::test::oracle_v_tex_min_i32(old, src); }
inline u32 v_tex_min_u32(u32 old, u32 src) { return lgpu::test::oracle_v_tex_min_u32(old, src); }
inline u32 v_tex_or_b32(u32 old, u32 src) { return lgpu::test::oracle_v_tex_or_b32(old, src); }
inline u32 v_tex_sub_i32(u32 old, u32 src) { return lgpu::test::oracle_v_tex_sub_i32(old, src); }
inline u32 v_tex_swap_b32(u32 old, u32 src) { return lgpu::test::oracle_v_tex_swap_b32(old, src); }
inline u32 v_tex_xor_b32(u32 old, u32 src) { return lgpu::test::oracle_v_tex_xor_b32(old, src); }
inline u32 wqm(u32 a) { return lgpu::test::oracle_wqm(a); }
inline u32 f32_add(u32 a, u32 b, lgpu::test::FpPolicy policy) { return lgpu::test::sf_add32(a, b, policy); }
inline u64 f64_add(u64 a, u64 b, lgpu::test::FpPolicy policy) { return lgpu::test::sf_add64(a, b, policy); }
inline u32 f32_ceil(u32 a, lgpu::test::FpPolicy policy) { return lgpu::test::sf_ceil32(a, policy); }
inline u64 f64_ceil(u64 a, const lgpu::test::FpPolicy& p1) { return lgpu::test::sf_ceil64(a, p1); }
inline u32 f32_copysign(u32 a, u32 b, lgpu::test::FpPolicy policy) { return lgpu::test::sf_copysign32(a, b, policy); }
inline u32 f32_cos(u32 a, const lgpu::test::FpPolicy& p1) { return lgpu::test::sf_cos32(a, p1); }
inline u32 f32_exp2_(u32 a, const lgpu::test::FpPolicy& p1) { return lgpu::test::sf_exp2_32(a, p1); }
inline u32 f16_f32(u32 a, lgpu::test::FpPolicy policy) { return lgpu::test::sf_f16_f32(a, policy); }
inline u32 f32_f16(u32 a, lgpu::test::FpPolicy policy) { return lgpu::test::sf_f32_f16(a, policy); }
inline u64 f32_f64(u32 a) { return lgpu::test::sf_f32_f64(a); }
inline u32 f32_i32(u32 a, lgpu::test::FpPolicy policy) { return lgpu::test::sf_f32_i32(a, policy); }
inline u32 f32_u32(u32 a, lgpu::test::FpPolicy policy) { return lgpu::test::sf_f32_u32(a, policy); }
inline u32 f64_f32(u64 a) { return lgpu::test::sf_f64_f32(a); }
inline u32 f64_i32(u64 a, lgpu::test::FpPolicy policy) { return lgpu::test::sf_f64_i32(a, policy); }
inline u32 f64_u32(u64 a, lgpu::test::FpPolicy policy) { return lgpu::test::sf_f64_u32(a, policy); }
inline u32 f32_floor(u32 a, lgpu::test::FpPolicy policy) { return lgpu::test::sf_floor32(a, policy); }
inline u64 f64_floor(u64 a, const lgpu::test::FpPolicy& p1) { return lgpu::test::sf_floor64(a, p1); }
inline u32 f32_fma(u32 a, u32 b, u32 c, const lgpu::test::FpPolicy& p3) { return lgpu::test::sf_fma32(a, b, c, p3); }
inline u64 f64_fma(u64 a, u64 b, u64 c, lgpu::test::FpPolicy policy) { return lgpu::test::sf_fma64(a, b, c, policy); }
inline u32 f32_fract(u32 a, lgpu::test::FpPolicy policy) { return lgpu::test::sf_fract32(a, policy); }
inline u64 f64_fract(u64 a, const lgpu::test::FpPolicy& p1) { return lgpu::test::sf_fract64(a, p1); }
inline u32 i32_f32(u32 a, lgpu::test::FpPolicy policy) { return lgpu::test::sf_i32_f32(a, policy); }
inline u64 i32_f64(u32 a) { return lgpu::test::sf_i32_f64(a); }
inline u32 f32_ldexp(u32 a, u32 e, const lgpu::test::FpPolicy& p2) { return lgpu::test::sf_ldexp32(a, e, p2); }
inline u64 f64_ldexp(u64 a, u32 exp) {
  // [HW 2026-08-24] zero stays zero; the rest of the ldexp behavior
  // (signed exponent, extremes, denormal flush) lives in sf_ldexp64.
  if ((a & 0x7fffffffffffffffull) == 0ull)
    return a;
  u64 r = lgpu::test::sf_ldexp64(a, exp);
  if ((r & 0x7ff0000000000000ull) == 0 &&
      (r & 0x000fffffffffffffull) != 0)
    r &= 0x8000000000000000ull;
  return r;
}
inline u32 f32_log2_(u32 a, const lgpu::test::FpPolicy& p1) { return lgpu::test::sf_log2_32(a, p1); }
inline u32 f32_max3(u32 a, u32 b, u32 c, lgpu::test::FpPolicy policy) { return lgpu::test::sf_max3(a, b, c, policy); }
inline u32 f32_max(u32 a, u32 b, lgpu::test::FpPolicy policy) { return lgpu::test::sf_max32(a, b, policy); }
inline u64 f64_max(u64 a, u64 b) { return lgpu::test::sf_max64(a, b); }
inline u32 f32_med3(u32 a, u32 b, u32 c, lgpu::test::FpPolicy policy) { return lgpu::test::sf_med3(a, b, c, policy); }
inline u32 f32_min3(u32 a, u32 b, u32 c, lgpu::test::FpPolicy policy) { return lgpu::test::sf_min3(a, b, c, policy); }
inline u32 f32_min(u32 a, u32 b, lgpu::test::FpPolicy policy) { return lgpu::test::sf_min32(a, b, policy); }
inline u64 f64_min(u64 a, u64 b) { return lgpu::test::sf_min64(a, b); }
inline u32 f32_mul(u32 a, u32 b, lgpu::test::FpPolicy policy) { return lgpu::test::sf_mul32(a, b, policy); }
inline u64 f64_mul(u64 a, u64 b, lgpu::test::FpPolicy policy) { return lgpu::test::sf_mul64(a, b, policy); }
inline u32 f32_rcp(u32 a, const lgpu::test::FpPolicy& p1) { return lgpu::test::sf_rcp32(a, p1); }
inline u64 f64_rcp(u64 a, const lgpu::test::FpPolicy& p1) { return lgpu::test::sf_rcp64(a, p1); }
inline u32 f32_revsub(u32 a, u32 b, lgpu::test::FpPolicy policy) { return lgpu::test::sf_revsub32(a, b, policy); }
inline u32 f32_rndne(u32 a, lgpu::test::FpPolicy policy) { return lgpu::test::sf_rndne32(a, policy); }
inline u64 f64_rndne(u64 a, const lgpu::test::FpPolicy& p1) { return lgpu::test::sf_rndne64(a, p1); }
inline u32 f32_rsq(u32 a, const lgpu::test::FpPolicy& p1) { return lgpu::test::sf_rsq32(a, p1); }
inline u64 f64_rsq(u64 a, const lgpu::test::FpPolicy& p1) { return lgpu::test::sf_rsq64(a, p1); }
inline u32 f32_sin(u32 a, const lgpu::test::FpPolicy& p1) { return lgpu::test::sf_sin32(a, p1); }
inline u32 f32_sqrt(u32 a, lgpu::test::FpPolicy policy) { return lgpu::test::sf_sqrt32(a, policy); }
inline u64 f64_sqrt(u64 a, lgpu::test::FpPolicy policy) { return lgpu::test::sf_sqrt64(a, policy); }
inline u32 f32_sub(u32 a, u32 b, lgpu::test::FpPolicy policy) { return lgpu::test::sf_sub32(a, b, policy); }
inline u32 f32_trunc(u32 a, lgpu::test::FpPolicy policy) { return lgpu::test::sf_trunc32(a, policy); }
inline u64 f64_trunc(u64 a, const lgpu::test::FpPolicy& p1) { return lgpu::test::sf_trunc64(a, p1); }
inline u32 u32_f32(u32 a, lgpu::test::FpPolicy policy) { return lgpu::test::sf_u32_f32(a, policy); }
inline u64 u32_f64(u32 a) { return lgpu::test::sf_u32_f64(a); }
