// Generated by tools/gen_registry.py. Do not edit by hand.
#pragma once
#include <cstdint>
#include <string>
#include <vector>
namespace lgpu::test { struct FpPolicy; }
namespace lgpu::ops {
using OpsFn = bool (*)(const std::vector<std::uint32_t>&,
                       const test::FpPolicy&,
                       std::vector<std::uint32_t>&);
OpsFn find_op(const std::string& mnemonic);
}  // namespace lgpu::ops
